site_name: Examen Unidad 6
site_url: https://oliviasgm.github.io/Examen/
docs_dir: 'docs_src'  
site_dir: 'docs'
nav:
  - Inicio: README.md
  - Guía de Instalación Windows 11: instalacion_windows11.md
  - Especificaciones Técnicas iPhone 16: especificaciones_iphone16.md

  - Descarga en pdf:
    - Guía de Instalación Windows 11: instalacion_windows11/instalacion_windows11.pdf
    - Especificaciones Técnicas iPhone 16: especificaciones_iphone16/especificaciones_iphone16.pdf
theme: 
  name: readthedocs
plugins:
  - search
  - pdf-export:
      enabled if_env: ENABLE_PDF_EXPORT
      media_type: print
  - with-pdf:
      author: Olivia Susana Guziak
      copyright: CCO 1.0 Universal
      cover: true
      back_cover: false
      cover_title: Examen Unidad 6
      cover_subtitle: Desarrollo interfaces -2º DAM
      toc_title: Índice
      toc_level: 2
      ordered_chapter_level: 2
